// src/server/entity/fixtures.ts
/** Draft 4 AR-XML フィクスチャ本文を URL パスへ明示対応付けする。 */
export const arxmlFixtures: Readonly<Record<string, string>> = {
  "/arxml/valid/single-output-json.arxml": "<?xml version=\"1.0\" encoding=\"UTF-8\"?><ar-entity xmlns=\"https://relink.dev/ns/arxml/core/0.1\" version=\"0.1\"><capabilities><capability id=\"temperature\" type=\"https://example.test/capabilities/temperature/read/1\"><result><outputs><output name=\"temperature\" type=\"number\" /></outputs><representations><representation media-type=\"application/json\" /></representations></result><interfaces><interface type=\"http\" method=\"GET\" endpoint=\"/api/json/single\" /></interfaces></capability></capabilities></ar-entity>",
  "/arxml/valid/multi-output-json.arxml": "<?xml version=\"1.0\"?><ar-entity xmlns=\"https://relink.dev/ns/arxml/core/0.1\" version=\"0.1\"><capabilities><capability id=\"climate\" type=\"https://example.test/capabilities/climate/read/1\"><result><outputs><output name=\"temperature\" type=\"number\" /><output name=\"humidity\" type=\"number\" /></outputs><representations><representation media-type=\"application/json\" /></representations></result><interfaces><interface type=\"http\" method=\"GET\" endpoint=\"/api/json/multi\" /></interfaces></capability></capabilities></ar-entity>",
  "/arxml/valid/post-json.arxml": "<?xml version=\"1.0\"?><ar-entity xmlns=\"https://relink.dev/ns/arxml/core/0.1\" version=\"0.1\"><capabilities><capability id=\"echo\" type=\"https://example.test/capabilities/search/echo/1\"><inputs><input name=\"query\" type=\"string\" required=\"true\" /></inputs><result><outputs><output name=\"query\" type=\"string\" /></outputs><representations><representation media-type=\"application/json\" /></representations></result><interfaces><interface type=\"http\" method=\"POST\" endpoint=\"/api/json/echo\" encoding=\"json\" /></interfaces></capability></capabilities></ar-entity>",
  "/arxml/valid/no-output-204.arxml": "<?xml version=\"1.0\"?><ar-entity xmlns=\"https://relink.dev/ns/arxml/core/0.1\" version=\"0.1\"><capabilities><capability id=\"empty\" type=\"https://example.test/capabilities/empty/1\"><result /><interfaces><interface type=\"http\" method=\"GET\" endpoint=\"/api/no-content\" /></interfaces></capability></capabilities></ar-entity>",
  "/arxml/valid/http-500.arxml": "<?xml version=\"1.0\"?><ar-entity xmlns=\"https://relink.dev/ns/arxml/core/0.1\" version=\"0.1\"><capabilities><capability id=\"failing-service\" type=\"https://example.test/capabilities/failing/1\"><result><outputs><output name=\"value\" type=\"number\" /></outputs><representations><representation media-type=\"application/json\" /></representations></result><interfaces><interface type=\"http\" method=\"GET\" endpoint=\"/api/status/500\" /></interfaces></capability></capabilities></ar-entity>",
  "/arxml/valid/malformed-json.arxml": "<?xml version=\"1.0\"?><ar-entity xmlns=\"https://relink.dev/ns/arxml/core/0.1\" version=\"0.1\"><capabilities><capability id=\"malformed-temperature\" type=\"https://example.test/capabilities/temperature/read/1\"><result><outputs><output name=\"temperature\" type=\"number\" /></outputs><representations><representation media-type=\"application/json\" /></representations></result><interfaces><interface type=\"http\" method=\"GET\" endpoint=\"/api/representation/malformed-json\" /></interfaces></capability></capabilities></ar-entity>",
  "/arxml/edge/relative-endpoint-invocable.arxml": "<?xml version=\"1.0\"?><ar-entity xmlns=\"https://relink.dev/ns/arxml/core/0.1\" version=\"0.1\"><capabilities><capability id=\"relative-temperature\" type=\"https://example.test/capabilities/temperature/read/1\"><result><outputs><output name=\"temperature\" type=\"number\" /></outputs><representations><representation media-type=\"application/json\" /></representations></result><interfaces><interface type=\"http\" method=\"GET\" endpoint=\"../../api/json/single\" /></interfaces></capability></capabilities></ar-entity>",
  "/arxml/invalid/malformed-xml.arxml": "<ar-entity",
  "/arxml/invalid/missing-capability-id.arxml": "<?xml version=\"1.0\"?><ar-entity xmlns=\"https://relink.dev/ns/arxml/core/0.1\" version=\"0.1\"><capabilities><capability type=\"https://example.test/capabilities/example/1\" /></capabilities></ar-entity>",
  "/arxml/invalid/missing-capability-type.arxml": "<?xml version=\"1.0\"?><ar-entity xmlns=\"https://relink.dev/ns/arxml/core/0.1\" version=\"0.1\"><capabilities><capability id=\"example\" /></capabilities></ar-entity>"
};
